{% set name = "robotframework-clang" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}
{% set py_min_num = "310" %}
{% set xeus_cpp_version = "0.8.0" %}
{% set clang_major_version = "20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  skip: true  # [py < {{ py_min_num }}]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python
    - robotframework
    - jupyter_client
    - docutils
    - xeus-cpp >={{ xeus_cpp_version }}
    - clang >={{ clang_major_version }},<{{ clang_major_version|int + 1 }}.0a0
    - libcxx

test:
  source_files:
    - docs
  requires:
    - python
    - robotframework
    - docutils
    - clang >={{ clang_major_version }},<{{ clang_major_version|int + 1 }}.0a0
    - xeus-cpp >={{ xeus_cpp_version }}
    - libcxx
  commands:
    - robot --extension rst docs/tests.rst

about:
  home: https://github.com/maxrossello/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Robot Framework library for Clang/C++ interaction via Xeus'
  dev_url: https://github.com/maxrossello/{{ name }}

extra:
  recipe-maintainers:
    - maxrossello