context:
  name: robotframework-clang
  version: "0.2.2"
  xeus_cpp_version: "0.8.0"
  clang_major: "20"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    # - ${{ stdlib("c") }} # Uncomment ONLY for conda-forge submission (causes 'undefined' locally)
    - clang ${{ clang_major }}.*  # [linux]
    - clangxx ${{ clang_major }}.* # [linux]
  host:
    - python
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python
    - robotframework
    - jupyter_client
    - docutils
    - xeus-cpp >=${{ xeus_cpp_version }}
    - clang ${{ clang_major }}.*
    - clangxx ${{ clang_major }}.*
    - libcxx # [linux]

tests:
  - script:
      - jupyter kernelspec list
      - robot --extension rst docs/tests.rst
    files:
      source:
        - docs
    requirements:
      run:
        - robotframework
        - clang ${{ clang_major }}.* # [win]
        - clangxx ${{ clang_major }}.* # [win]

about:
  homepage: https://github.com/maxrossello/robotframework-clang
  license: Apache-2.0
  license_file: LICENSE
  summary: Robot Framework library for Clang-REPL execution via xeus-cpp
  description: |
    robotframework-clang is a Robot Framework library designed to execute 
    and test C++ code interactively using Clang-REPL (via the xeus-cpp extension).
    It allows for JIT compilation, state persistence across tests, and full 
    support for modern C++ features.

extra:
  recipe-maintainers:
    - maxrossello
