# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      # Generate api.rst dynamically from source code
      - python utils/libdoc2rst.py

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# We explicitly declare python dependencies required to build the docs
# We install the package dependencies (robotframework, etc.) via requirements.txt
# so that libdoc2rst.py can import the library.
python:
  install:
    - requirements: docs/requirements.txt
