# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# We explicitly declare python dependencies required to build the docs
# We DO NOT install the package itself (method: pip) because it depends on 
# C++ binaries (xeus-cpp) not available on standard PyPI/RTD agents.
# Since api.rst is pre-generated and versioned, we only need Sphinx.
python:
  install:
    - requirements: docs/requirements.txt
